---
title: "GrassXTBG"
author: "WangJY"
date: "2022-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(stringr)
grass <-read_xlsx("data/XTBGPOACEAE.xlsx",sheet=1)
head(grass)
GrassDataset <- read.csv("data/GrassDataset.csv")
head(GrassDataset)
sum(grass$Poaceae%in%GrassDataset$Species_old)
sum(grass$Poaceae%in%GrassDataset$accepted_name)
for (i in 1:nrow(grass)){
  grass$Binomial[i] <- paste0(str_split(grass$Poaceae,pattern = " ",n=3)[[i]][1]," ",str_split(grass$Poaceae,pattern = " ",n=3)[[i]][2])
}
sum(grass$Binomial%in%GrassDataset$Species_old)
sum(grass$Binomial%in%GrassDataset$accepted_name)

library(tidyverse)
tmp <- GrassDataset[,c("Species_old","aridity.ch","accepted_name")]
colnames(tmp)[1]<- "Binomial"
grass <- left_join(grass,tmp[,1:2])
colnames(grass)[6]<-"aridity.index"

grasslist <- aggregate(grass,aridity.index~Binomial,FUN=mean)
grasslist <- inner_join(grasslist,grass)
write.csv(grasslist,"data/GrassInXTBG.csv",row.names=F)
hist(grasslist$aridity.index)
```
